language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ericwatts/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ericwatts/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-test"
  bucket_name: "elasticbeanstalk-us-west-2-296688327412"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
