language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ericwatts/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ericwatts/docker-react npm run test